name: Multi-Platform Verification & Code Coverage

on:
  push:
    tags:
      - wsio-client-v*
      - wsio-core-v*
      - wsio-server-v*
  workflow_dispatch: null

concurrency:
  group: ci-test-and-coverage
  cancel-in-progress: true

jobs:
  test:
    name: Rust on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run tests and show coverage
        run: cargo coverage

      - name: Generate lcov report
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cargo coverage-generate

      - name: Upload lcov report to codecov
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
          files: ./lcov.info
          flags: rust
          token: ${{ secrets.CODECOV_TOKEN }}
